name: Notificar a Discord en push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"🚀 Push hecho por $GITHUB_ACTOR en $GITHUB_REPOSITORY.\n🔗 https://github.com/$GITHUB_REPOSITORY/commits/$GITHUB_SHA\"}"
